# action.yml
name: 'Build mdbooks html documentation'
description: 'Builds html documentation using mdbooks and plugins '
inputs:
  input-dir:
    description: 'Path of mdbooks source'
    required: true
  output-dir:
    description: 'Path to write mdbooks output to'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-d"
    - ${{ inputs.output-dir }}
    - ${{ inputs.input-dir }}
